{% set name = "quantlab_launcher" %}
{% set version = "0.1.2" %}
{% set sha256 = "72906177c5ea234e5f62cc79c182e08fb19b0a1b16ac8c89777192bae152bfe4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - pip
    - python
    - setuptools
  run:
    - python
    - notebook >=4.2

test:
  imports:
    - quantlab_launcher

about:
  home: https://github.com/quantlabio/quantlab_launcher
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A Launcher for QuantLab based applications.

extra:
  recipe-maintainers:
    - lab4quant
