travis:
  secure:
    BINSTAR_TOKEN: QWKoPcspbVysXiUKj+Tm6EoiYYS1Sj3txVYu7LjBouFK9Ya9uoU7R1G8wT76RJ3vSwpq6xgkUFiY5DAj36kIfccoETfN3pG50irSoLJkBtYBuZYfranmTcAwmyQVDPKkKfHHR7mIsVGh+fmWThCLuj2bAjQysVL64458VzfWcDSYTCpzwvewkxCQ0E8Jjx8kJQRTu+2kn5WJa9NdoM//hLYPpjLSpZ12kQQvf5Rp6Z3fcC43S3THZKp6m/Ykiv7llHWdBZTU6AUP718cU/Gvrcv25RSO4YWQ5MFEn1QldhULsHad4sKlA1FJANMX+X9BkFipbTf6dfTNUGC86g4bgv3u8yznv5SKy3b2xzmC796amYJR0ZcELcO1cCRwY+oAFteb4VkyNcnZhs236BZA+l/7yGVhcOwAkWHsLhUM5WHZzm7cvOVR9UpmmUWWMTiKjzEqH604TimnwadyvX0oeau89DsFu3bj5Hfe2K87+CoXjKFZMoXl5HobGa3+u/9iV6ZXuy3Yg/moLfzax1wf+8wuGJMB/BxtUrom5ebXXGdC5BTAbXtJCLvtqZw7G0C4fcOLAE/JWQj5+4ib0N3SAFxP/J2RlnR9GdScqelRzwJYDGVPTLiFFP6FXDuOnXjG7IJGULGVGbIOOAY6njxhYOJ5KvEfL60dg9puaJEHwFo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
