travis:
  secure:
    BINSTAR_TOKEN: Rob7ZEyyHWyb+RAdm9EYHqUAuACs4ITikEuB4G0oV19jvuSjF9Aw6uWjRDIjRhrLM66eZ6MjluPCSGQ39Azh2JXzbzl5kz8x76YTSfrpZ+vhLSNGtAxCik/a7k4k2YiqzapEJ36+CViaZeDlbj2KMQh84fAZdR2k0emNXlhD6xpDipAWLuv+z6rf5UNDtcvJhyQPDVi9PCATmUU1svrPsx1rK1J8X6kyimSDwVXXBqgM/ad0B+fRaQRzPSMoTxEGR2MCKgDlLHkMeTeNC0UVPkzXXH2fC+aqTbJZYPNgAg/RE7NWC9Jb41RiDDS3roqwcbpeUga7E50pxNRVLGLA2GUUj4IiE0h9wAYpNJoSPW6ZI5wynCmZTsqsOoO21CmT+IyxkfWD/HWXLPxdgoTMwRGDDJf74TZWTMgme91MiKxkbRC4ZC5CXNdQlMt7oCFtRiwuf7aP5atVfGQ1MbU5Gd0NPR82zvExiGiWCN3YwoQu/tB8VXR7I1+RWRNMp6VKpErcz6zeJcopHuBjph7FeuJpxHYydE2/EmhtRSOjGkAEOrEwXy01kTmhHa4PTjJesOOMHs51LWPbNoJUXNDzRionhrkneSWqBilEsl2jtMEmbrbGxZhz8zzIcHHPYl+fdJrUSAn4GPv+i+l6JRzLDQxpoJhw3n0m1dZGC+4L0G0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
